### ISSUE TITLE
handlebars event handlers feedback loop

### ISSUE THREAD

**Issue by dvdpwll** [ga-wdi-boston/group-project#159] opened 2016-09-07 17:26 UTC
we're having trouble showing changes to content after doing a get request. The display function is below the refresh page functions, but refresh needs to call the display function. We're creating a function loop and we're not sure how to show the changes.

**Comment by gaand** [comment] 2016-09-07 17:29
Code please?

**Comment by gabescarbrough** [comment] 2016-09-07 17:33
``` js
const displayUserFile = function(data){
  console.log(data);
  let userFileTemplate = require('./templates/current-user-file.handlebars');
    $('#main-content').append(userFileTemplate({
      files: data.files
    }));
    $('.rename-button').on('click', function(){
      let fileId = $(this).data('file-id');
      console.log(fileId);
      let newName = $(this).prev().val();
      console.log(newName);

      let data = {
        "file" : {
          "name": newName,
        }
      };

      api.renameFile(data, fileId)
        .done(refreshPage)
        .fail(ui.onError);
    });
    $('.delete-button').on('click', function(){
      let fileId = $(this).data('file-id');
      console.log(fileId);
      api.deleteFile(fileId)
        .done(refreshPage)
        .fail(ui.onError);

    });
};

const refreshPage = function() {
  let path = app.currentPath;

  console.log(path);

  api.showRootFolder(path)
    .done(displayUserFolder)
    .fail();
  api.showRootFiles(path)
    .done(displayUserFile)
    .fail();
};
```

``` js
const showRootFolder = (path) => $.ajax({
  url: app.api + '/rootfolders/' + path,
  method: 'GET',
});
```

**Comment by dvdpwll** [comment] 2016-09-07 17:35
displayUserFiles -> refreshPage -> displayUserFiles

We're not sure how to display files again after getting the changes w/o going back to displayUserFiles

**Comment by gaand** [comment] 2016-09-07 17:39
First, do something on fail.

Second, I'm still not understanding.  Is the flow you posted correct?  Are there functions missing that are part of this flow?

**Comment by gaand** [comment] 2016-09-07 17:40
Also, the order in which `displayUserFolder` and `displayUserFile` runs is not well defined.

**Comment by gabescarbrough** [comment] 2016-09-07 17:48
When you sign in a function called getRootFolder sets the currentPath to the signed in user's root folder. Then it sends that to getRootContents which gets the contents of that folder. On done that info is sent to displayUserFolder and displayUserFile which both use Handlebars templates to show that info on the screen and apply click handlers for edit and delete buttons.

The issue is that when you click on an edit or delete button they work, but the info on the page is not refreshed, but to go through the templates apply click handlers you need to pass the info to the function you are currently in.

Hence the refreshPage function which was meant to get out of that, but we're finding it is still ending up in a loop.

**Comment by RealWeeks** [comment] 2016-09-07 17:49
Why not just remove/edit the item with jquery and when the user revisits the page show them the refreshed data?

**Comment by gaand** [comment] 2016-09-07 17:51
Can the DOM be updated directly?

**Comment by gabescarbrough** [comment] 2016-09-07 17:54
@J-Weeks I think that would work.

@gaand I'm not sure what you mean. I believe we can target them using jQuery to hide (when something is deleted) or display the new name (on rename).

**Comment by gaand** [comment] 2016-09-07 18:11
Why not remove, rather than hide?

**Comment by gabescarbrough** [comment] 2016-09-07 18:12
We could use remove.

Won't we run into a similar issue for showing other folders contents though? We can get the contents of any folder by path but we need to show it in the DOM by passing it through the template.

**Comment by gaand** [comment] 2016-09-07 19:16
Let's discuss briefly.

**Comment by gaand** [comment] 2016-09-07 19:33
Suggested looking at handling bubbled events and handlebars partials.

**Comment by gaand** [comment] 2016-10-07 14:12
Closing after end of cohort 013.

**Closed as completed by gaand** 2016-10-07 14:12 UTC
