### ISSUE TITLE
Emphasize not avoiding your weaknesses in group project 

### ISSUE THREAD

**Issue by BenGitsCode** [ga-wdi-boston/group-project#215] opened 2016-12-21 18:22 UTC
Group projects should EXPOSE and STRENGTHEN your weaknesses, NOT just play to your strengths.

**Comment by raq929** [comment] 2017-01-05 22:02
This is a duplicate of #216.  (Which has a bit more information, so I'm keeping that one.)

**Closed as completed by raq929** 2017-01-05 22:02 UTC
Labels: duplicate

**Comment by BenGitsCode** [comment] 2017-01-06 14:33
@bengitscode Approves this close 👍
